
server:
  port: 8884
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/
zuul:
  routes:
    locallife:
      path: /locallife/**
      serviceId: xiangyanjun-locallife
    common:
      path: /common/**
      serviceId: xiangyanjun-common

